# Nairobi City County Own Source Revenue Business Intelligence System

## Notebook 01: Data Understanding

### Author
Erastus Okomo

### Project
Nairobi City County Own Source Revenue Business Intelligence System

### Project Objective
The objective of this notebook is to understand the structure, quality, and business meaning of the Nairobi City County Own Source Revenue dataset before carrying out data cleaning, transformation, and analysis.

# 1. Import Libraries

This section imports all Python libraries required for loading, exploring, and understanding the dataset.

In [7]:
# ======================================================
# IMPORT LIBRARIES
# ======================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns when viewing dataframes
pd.set_option("display.max_columns", None)

# Display numbers with commas and two decimal places
pd.options.display.float_format = "{:,.2f}".format

### Observation

The required libraries were successfully imported. Pandas will be used for data manipulation, NumPy for numerical operations, and Matplotlib/Seaborn for visualization in later stages of the project.

# 2. Load Dataset

In this section, we load the original revenue dataset from the raw data folder into a Pandas DataFrame. This is the first step in the ETL (Extract, Transform, Load) process.

In [14]:
# ======================================================
# LOAD DATASET
# ======================================================

# File path
file_path = "/Users/mac/Documents/Economic Planning Docs/Nairobi_OSR_BI_Project/data/raw/OSR2025JUNE30.xlsx"

# Read the Excel file
df = pd.read_excel(file_path)

# Display the first five rows
df.head(20)

,REVENUE COLLECTIONS FY 2024/2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Revenue Stream,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,NaN
1,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67"
2,Parking fees (total),403102547,415717240,624117208,467616505,"1,910,553,500.00"
3,Unified Business permit,268881225,322159358,1363055364,644656753,"2,598,752,700.00"
4,Plans and Inspections (Building Permits),434454160,421195656,316879305,286453495,"1,458,982,616.00"
5,Billboards and advertisements,96830108,188022729,205184225,153075885,"643,112,947.00"
6,House and Stall Rent,109158566,180840370,147219979,337569050,"774,787,965.00"
7,Fire Inspection Certificates,761000,566500,2754000,1285000,"5,366,500.00"
8,Food Handlers Certificates,22673506,18433500,30551510,25270550,"96,929,066.00"
9,Markets,44760036,50097349,45997986,50544341,"191,399,712.00"
10,Other Incomes/Unallocated,"262,110,272.28","212,776,330.58","237,211,004.32","239,130,607.02","951,228,214.20"
11,NaN,"1,838,806,012.70","1,952,172,916.68","4,947,357,982.23","3,179,745,547.26","11,918,082,458.87"
12,Liquor Board Revenue,76489325,73105351,90546930,98450355,"338,591,961.00"
13,Pumwani,16489785,76640479,91908515,53040837,"238,079,616.00"
14,Mbagathi,140644661,131439322,"84,215,086.50",104311777,"460,610,846.50"
15,Mama Lucy,133213418,169692979,138099147,134383277,"575,388,821.00"
16,Mutuini,16598278,22105802,18481504,27436995,"84,622,579.00"
17,Nairobi Funeral Home,6940180,8831530,12063637,11509388,"39,344,735.00"
18,NaN,"2,229,181,659.70","2,433,988,379.68","5,382,672,801.73","3,608,878,176.26","13,654,721,017.37"

In [30]:
df = pd.read_excel(file_path, header=1)
df.rename(columns={"Unnamed: 5": "Total"}, inplace=True)
df.head(18)

,Revenue Stream,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,Total
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67"
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00"
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00"
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00"
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00"
5,House and Stall Rent,"109,158,566.00","180,840,370.00","147,219,979.00","337,569,050.00","774,787,965.00"
6,Fire Inspection Certificates,"761,000.00","566,500.00","2,754,000.00","1,285,000.00","5,366,500.00"
7,Food Handlers Certificates,"22,673,506.00","18,433,500.00","30,551,510.00","25,270,550.00","96,929,066.00"
8,Markets,"44,760,036.00","50,097,349.00","45,997,986.00","50,544,341.00","191,399,712.00"
9,Other Incomes/Unallocated,"262,110,272.28","212,776,330.58","237,211,004.32","239,130,607.02","951,228,214.20"
10,NaN,"1,838,806,012.70","1,952,172,916.68","4,947,357,982.23","3,179,745,547.26","11,918,082,458.87"
11,Liquor Board Revenue,"76,489,325.00","73,105,351.00","90,546,930.00","98,450,355.00","338,591,961.00"
12,Pumwani,"16,489,785.00","76,640,479.00","91,908,515.00","53,040,837.00","238,079,616.00"
13,Mbagathi,"140,644,661.00","131,439,322.00","84,215,086.50","104,311,777.00","460,610,846.50"
14,Mama Lucy,"133,213,418.00","169,692,979.00","138,099,147.00","134,383,277.00","575,388,821.00"
15,Mutuini,"16,598,278.00","22,105,802.00","18,481,504.00","27,436,995.00","84,622,579.00"
16,Nairobi Funeral Home,"6,940,180.00","8,831,530.00","12,063,637.00","11,509,388.00","39,344,735.00"
17,NaN,"2,229,181,659.70","2,433,988,379.68","5,382,672,801.73","3,608,878,176.26","13,654,721,017.37"

In [19]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [10]:
import openpyxl

print(openpyxl.__version__)

3.1.5

# 3. Dataset Exploration

In this section, we explore the structure of the dataset to understand its dimensions, variables, data types, and overall quality before conducting further analysis.

In [15]:
# ======================================================
# DATASET DIMENSIONS
# ======================================================

print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 19
Number of Columns : 6

In [16]:
# ======================================================
# COLUMN NAMES
# ======================================================

df.columns

Index(['REVENUE COLLECTIONS FY 2024/2025 ', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'],
      dtype='str')

# 4. Dataset Structure and Exploration

The purpose of this section is to understand the overall structure of the dataset. We examine the number of observations, variables, column names, data types, and basic descriptive statistics to ensure the dataset has been correctly imported.

In [24]:
# ======================================================
# DATASET DIMENSIONS
# ======================================================

rows, columns = df.shape

print("="*40)
print("DATASET DIMENSIONS")
print("="*40)
print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

========================================
DATASET DIMENSIONS
========================================
Number of Rows    : 18
Number of Columns : 6

In [25]:
# ======================================================
# COLUMN NAMES
# ======================================================

print("="*40)
print("COLUMN NAMES")
print("="*40)

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

========================================
COLUMN NAMES
========================================
1. Revenue Stream
2. 1st Quarter
3. 2nd Quarter
4. 3rd Quarter
5. 4th Quarter
6. Total

In [26]:
# ======================================================
# DATA TYPES
# ======================================================

print("="*40)
print("DATA TYPES")
print("="*40)

df.info()

========================================
DATA TYPES
========================================
<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Revenue Stream  16 non-null     str
 1   1st Quarter     18 non-null     float64
 2   2nd Quarter     18 non-null     float64
 3   3rd Quarter     18 non-null     float64
 4   4th Quarter     18 non-null     float64
 5   Total           18 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.3 KB

In [27]:
# ======================================================
# SUMMARY STATISTICS
# ======================================================

df.describe()

,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,Total
count,18.00,18.00,18.00,18.00,18.00
mean,"349,842,740.67","378,897,204.22","872,927,976.98","577,638,994.43","2,179,306,916.31"
std,"629,935,029.58","677,341,683.19","1,647,563,548.28","1,058,137,478.60","3,978,086,010.07"
min,"761,000.00","566,500.00","2,754,000.00","1,285,000.00","5,366,500.00"
25%,"28,195,138.50","55,849,349.50","55,552,261.12","51,168,465.00","203,069,688.00"
50%,"121,185,992.00","156,028,431.55","142,659,563.00","143,729,581.00","609,250,884.00"
75%,"267,188,486.82","294,813,601.14","547,307,732.25","435,104,641.25","1,797,660,779.00"
max,"2,229,181,659.70","2,433,988,379.68","5,382,672,801.73","3,608,878,176.26","13,654,721,017.37"

In [28]:
# ======================================================
# LAST FIVE RECORDS
# ======================================================

df.tail()

,Revenue Stream,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,Total
13,Mbagathi,"140,644,661.00","131,439,322.00","84,215,086.50","104,311,777.00","460,610,846.50"
14,Mama Lucy,"133,213,418.00","169,692,979.00","138,099,147.00","134,383,277.00","575,388,821.00"
15,Mutuini,"16,598,278.00","22,105,802.00","18,481,504.00","27,436,995.00","84,622,579.00"
16,Nairobi Funeral Home,"6,940,180.00","8,831,530.00","12,063,637.00","11,509,388.00","39,344,735.00"
17,NaN,"2,229,181,659.70","2,433,988,379.68","5,382,672,801.73","3,608,878,176.26","13,654,721,017.37"

In [29]:
# ======================================================
# MISSING VALUES
# ======================================================

df.isnull().sum()

Revenue Stream    2
1st Quarter       0
2nd Quarter       0
3rd Quarter       0
4th Quarter       0
Total             0
dtype: int64

# 5. Initial Data Cleaning

The dataset contains summary rows (subtotal and grand total) where the Revenue Stream field is blank (`NaN`). These rows are intended for reporting purposes and do not represent individual revenue streams. They are removed to prevent double counting during analysis and dashboard development.

In [31]:
# ======================================================
# CHECK MISSING REVENUE STREAMS
# ======================================================

missing_revenue_streams = df["Revenue Stream"].isna().sum()

print(f"Rows with missing Revenue Stream: {missing_revenue_streams}")

Rows with missing Revenue Stream: 2

In [32]:
# ======================================================
# REMOVE SUMMARY ROWS
# ======================================================

df = df.dropna(subset=["Revenue Stream"])

print("Updated Dataset Shape:", df.shape)

Updated Dataset Shape: (16, 6)

In [34]:
df["Revenue Stream"].isna().sum()

np.int64(0)

In [37]:
# ======================================================
# RESET INDEX
# ======================================================

df.reset_index(drop=True, inplace=True)

df.head(16)
df.tail()

,Revenue Stream,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,Total
11,Pumwani,"16,489,785.00","76,640,479.00","91,908,515.00","53,040,837.00","238,079,616.00"
12,Mbagathi,"140,644,661.00","131,439,322.00","84,215,086.50","104,311,777.00","460,610,846.50"
13,Mama Lucy,"133,213,418.00","169,692,979.00","138,099,147.00","134,383,277.00","575,388,821.00"
14,Mutuini,"16,598,278.00","22,105,802.00","18,481,504.00","27,436,995.00","84,622,579.00"
15,Nairobi Funeral Home,"6,940,180.00","8,831,530.00","12,063,637.00","11,509,388.00","39,344,735.00"

In [39]:
# Create a cleaned copy of the raw dataset
df_clean = df.copy()

# Remove summary rows
df_clean = df_clean.dropna(subset=["Revenue Stream"])

# Reset the index
df_clean.reset_index(drop=True, inplace=True)

# 6. Data Quality Assessment

This section evaluates the quality of the cleaned dataset by checking for duplicate records, missing values, incorrect data types, and consistency of quarterly revenue figures. The objective is to ensure that the dataset is suitable for analysis and dashboard development.

In [40]:
# ======================================================
# DUPLICATE RECORDS
# ======================================================

duplicates = df_clean.duplicated().sum()

print("="*50)
print("DUPLICATE RECORDS")
print("="*50)
print(f"Duplicate Records Found: {duplicates}")

==================================================
DUPLICATE RECORDS
==================================================
Duplicate Records Found: 0

In [41]:
# ======================================================
# MISSING VALUES
# ======================================================

missing = df_clean.isnull().sum()

print("="*50)
print("MISSING VALUES")
print("="*50)

print(missing)

==================================================
MISSING VALUES
==================================================
Revenue Stream    0
1st Quarter       0
2nd Quarter       0
3rd Quarter       0
4th Quarter       0
Total             0
dtype: int64

In [42]:
# ======================================================
# DATA TYPES
# ======================================================

print(df_clean.dtypes)

Revenue Stream        str
1st Quarter       float64
2nd Quarter       float64
3rd Quarter       float64
4th Quarter       float64
Total             float64
dtype: object

In [49]:
df_clean.columns.tolist()

['Revenue_Stream', 'Q1', 'Q2', 'Q3', 'Q4', 'Total']

In [47]:
df_clean.columns = [
    "Revenue_Stream",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "Total"
]

In [48]:
df.head()

,Revenue Stream,1st Quarter,2nd Quarter,3rd Quarter,4th Quarter,Total
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67"
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00"
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00"
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00"
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00"

In [50]:
# ======================================================
# VALIDATE TOTAL COLUMN
# ======================================================

df_clean["Calculated_Total"] = (
    df_clean["Q1"] +
    df_clean["Q2"] +
    df_clean["Q3"] +
    df_clean["Q4"]
)

comparison = (
    df_clean["Calculated_Total"] ==
    df_clean["Total"]
)

print("All totals correct:", comparison.all())

All totals correct: True

In [51]:
# ======================================================
# SAVE CLEAN DATASET
# ======================================================

output_path = "../data/processed/OSR2025JUNE30_Clean.xlsx"

df_clean.to_excel(output_path, index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!