# Nairobi City County Own Source Revenue Business Intelligence System

# Notebook 03: KPI Engineering and Business Metrics

## Author

Erastus Okomo

### Project
Nairobi City County Own Source Revenue Business Intelligence System

## Objective

This notebook develops Key Performance Indicators (KPIs) that summarize the financial performance of Nairobi City County's Own Source Revenue collection. These KPIs will later be integrated into an interactive Business Intelligence dashboard.

In [1]:
# ==========================================================
# IMPORT LIBRARIES
# ==========================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib.ticker import FuncFormatter

pd.set_option("display.max_columns", None)
pd.options.display.float_format = "{:,.2f}".format

sns.set_style("whitegrid")

In [2]:
# ==========================================================
# LOAD DATA
# ==========================================================

file_path = "../data/processed/OSR2025JUNE30_Clean.xlsx"

df = pd.read_excel(file_path)

df.head()

,Revenue_Stream,Q1,Q2,Q3,Q4,Total,Calculated_Total
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67","3,286,969,238.67"
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00","1,910,553,500.00"
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00","2,598,752,700.00"
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00","1,458,982,616.00"
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00","643,112,947.00"

In [22]:
# ==========================================================
# CREATE CONTRIBUTION PERCENTAGE
# ==========================================================

df["Contribution (%)"] = (
    df["Total"] / df["Total"].sum()
) * 100

df.head()

,Revenue_Stream,Q1,Q2,Q3,Q4,Total,Calculated_Total,Rank,Contribution (%)
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67","3,286,969,238.67",1,24.07
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00","1,910,553,500.00",3,13.99
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00","2,598,752,700.00",2,19.03
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00","1,458,982,616.00",4,10.68
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00","643,112,947.00",7,4.71

## KPI 1 — Total Own Source Revenue

In [3]:
total_revenue = df["Total"].sum()

print(f"Total Revenue: KES {total_revenue:,.2f}")

Total Revenue: KES 13,654,721,017.37

## KPI 2 — Number of Revenue Streams

In [4]:
total_streams = df["Revenue_Stream"].nunique()

print(f"Revenue Streams: {total_streams}")

Revenue Streams: 16

## KPI 3 — Average Revenue per Stream

In [5]:
average_revenue = df["Total"].mean()

print(f"Average Revenue: KES {average_revenue:,.2f}")

Average Revenue: KES 853,420,063.59

## KPI 4 — Highest Revenue Stream

In [7]:
highest = df.loc[df["Total"].idxmax()]

highest

print(f"Highest Revenue Stream : {highest['Revenue_Stream']}")

print(f"Revenue : KES {highest['Total']:,.2f}")

Highest Revenue Stream : Land Rates
Revenue : KES 3,286,969,238.67

## KPI 5 — Lowest Revenue Stream

In [8]:
lowest = df.loc[df["Total"].idxmin()]

print(f"Lowest Revenue Stream : {lowest['Revenue_Stream']}")

print(f"Revenue : KES {lowest['Total']:,.2f}")

Lowest Revenue Stream : Fire Inspection Certificates
Revenue : KES 5,366,500.00

## KPI 6 — Revenue Concentration

In [9]:
top5 = (
    df
    .sort_values("Total", ascending=False)
    .head(5)
)

top5_percentage = (
    top5["Total"].sum()
    /
    total_revenue
) * 100

print(f"Top Five Streams Contribute {top5_percentage:.2f}% of Total Revenue")

Top Five Streams Contribute 74.75% of Total Revenue

## KPI 7 — Quarter Performance

In [10]:
quarter_totals = df[
    ["Q1","Q2","Q3","Q4"]
].sum()

quarter_totals

Q1   2,229,181,659.70
Q2   2,433,988,379.68
Q3   5,382,672,801.73
Q4   3,608,878,176.26
dtype: float64

In [11]:
best_quarter = quarter_totals.idxmax()

best_value = quarter_totals.max()

print(best_quarter)

print(best_value)

Q3
5382672801.7300005

## KPI 8 — Quarter Contribution

In [12]:
quarter_summary = pd.DataFrame({
    "Revenue": quarter_totals
})

quarter_summary["Contribution (%)"] = (
    quarter_summary["Revenue"]
    /
    quarter_summary["Revenue"].sum()
) * 100

quarter_summary

            Revenue  Contribution (%)
Q1 2,229,181,659.70             16.33
Q2 2,433,988,379.68             17.83
Q3 5,382,672,801.73             39.42
Q4 3,608,878,176.26             26.43

In [13]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Revenue Streams",
        "Average Revenue",
        "Highest Revenue Stream",
        "Lowest Revenue Stream",
        "Top 5 Contribution (%)"
    ],
    "Value": [
        f"KES {total_revenue:,.2f}",
        total_streams,
        f"KES {average_revenue:,.2f}",
        highest["Revenue_Stream"],
        lowest["Revenue_Stream"],
        f"{top5_percentage:.2f}%"
    ]
})

kpi_summary

                      KPI                         Value
0           Total Revenue         KES 13,654,721,017.37
1         Revenue Streams                            16
2         Average Revenue            KES 853,420,063.59
3  Highest Revenue Stream                    Land Rates
4   Lowest Revenue Stream  Fire Inspection Certificates
5  Top 5 Contribution (%)                        74.75%

## KPI Function

In [16]:
# ==========================================================
# KPI FUNCTIONS
# ==========================================================

def total_revenue(df):
    return df["Total"].sum()


def average_revenue(df):
    return df["Total"].mean()


def revenue_streams(df):
    return df["Revenue_Stream"].nunique()


def highest_stream(df):
    return df.loc[df["Total"].idxmax()]


def lowest_stream(df):
    return df.loc[df["Total"].idxmin()]

total_revenue(df)

np.float64(13654721017.37)

## Executive KPIs

In [17]:
# ==========================================================
# EXECUTIVE KPIs
# ==========================================================

total_osr = total_revenue(df)

avg_osr = average_revenue(df)

streams = revenue_streams(df)

highest = highest_stream(df)

lowest = lowest_stream(df)

## Create executive scorecard

In [18]:
scorecard = pd.DataFrame({

"KPI":[

"Total Revenue",

"Revenue Streams",

"Average Revenue",

"Highest Revenue Stream",

"Highest Revenue",

"Lowest Revenue Stream",

"Lowest Revenue"

],

"Value":[

total_osr,

streams,

avg_osr,

highest["Revenue_Stream"],

highest["Total"],

lowest["Revenue_Stream"],

lowest["Total"]

]

})

scorecard

                      KPI                         Value
0           Total Revenue             13,654,721,017.37
1         Revenue Streams                            16
2         Average Revenue                853,420,063.59
3  Highest Revenue Stream                    Land Rates
4         Highest Revenue              3,286,969,238.67
5   Lowest Revenue Stream  Fire Inspection Certificates
6          Lowest Revenue                  5,366,500.00

## Revenue Ranking

In [19]:
df["Rank"] = (

df["Total"]

.rank(

ascending=False,

method="dense"

)

.astype(int)

)

df.sort_values("Rank").head(10)

,Revenue_Stream,Q1,Q2,Q3,Q4,Total,Calculated_Total,Rank
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67","3,286,969,238.67",1
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00","2,598,752,700.00",2
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00","1,910,553,500.00",3
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00","1,458,982,616.00",4
9,Other Incomes/Unallocated,"262,110,272.28","212,776,330.58","237,211,004.32","239,130,607.02","951,228,214.20","951,228,214.20",5
5,House and Stall Rent,"109,158,566.00","180,840,370.00","147,219,979.00","337,569,050.00","774,787,965.00","774,787,965.00",6
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00","643,112,947.00",7
13,Mama Lucy,"133,213,418.00","169,692,979.00","138,099,147.00","134,383,277.00","575,388,821.00","575,388,821.00",8
12,Mbagathi,"140,644,661.00","131,439,322.00","84,215,086.50","104,311,777.00","460,610,846.50","460,610,846.50",9
10,Liquor Board Revenue,"76,489,325.00","73,105,351.00","90,546,930.00","98,450,355.00","338,591,961.00","338,591,961.00",10

## Perfomance Classification

In [23]:
conditions = [

df["Contribution (%)"] >= 15,

df["Contribution (%)"] >= 5,

df["Contribution (%)"] < 5

]

choices = [

"High",

"Medium",

"Low"

]

df["Performance"] = np.select(

conditions,

choices,

default="Low"

)

df.head()

,Revenue_Stream,Q1,Q2,Q3,Q4,Total,Calculated_Total,Rank,Contribution (%),Performance
0,Land Rates,"196,074,592.42","142,363,884.10","1,974,387,400.91","974,143,361.24","3,286,969,238.67","3,286,969,238.67",1,24.07,High
1,Parking fees (total),"403,102,547.00","415,717,240.00","624,117,208.00","467,616,505.00","1,910,553,500.00","1,910,553,500.00",3,13.99,Medium
2,Unified Business permit,"268,881,225.00","322,159,358.00","1,363,055,364.00","644,656,753.00","2,598,752,700.00","2,598,752,700.00",2,19.03,High
3,Plans and Inspections (Building Permits),"434,454,160.00","421,195,656.00","316,879,305.00","286,453,495.00","1,458,982,616.00","1,458,982,616.00",4,10.68,Medium
4,Billboards and advertisements,"96,830,108.00","188,022,729.00","205,184,225.00","153,075,885.00","643,112,947.00","643,112,947.00",7,4.71,Low

## Revenue dependancy

In [24]:
top5 = (

df

.sort_values("Total",ascending=False)

.head(5)

)

dependency = (

top5["Total"].sum()

/

total_osr

)*100

print(dependency)

74.74694104615142

## Quarter perfomance index

In [25]:
quarter_totals = df[

["Q1","Q2","Q3","Q4"]

].sum()

quarter_index = pd.DataFrame({

"Quarter":quarter_totals.index,

"Revenue":quarter_totals.values

})

quarter_index["Rank"] = (

quarter_index["Revenue"]

.rank(

ascending=False,

method="dense"

)

.astype(int)

)

quarter_index

  Quarter          Revenue  Rank
0      Q1 2,229,181,659.70     4
1      Q2 2,433,988,379.68     3
2      Q3 5,382,672,801.73     1
3      Q4 3,608,878,176.26     2

## Executive Summary

In [26]:
print("="*60)

print("EXECUTIVE REVENUE SUMMARY")

print("="*60)

print(f"Total Revenue : KES {total_osr:,.2f}")

print(f"Revenue Streams : {streams}")

print(f"Average Revenue : KES {avg_osr:,.2f}")

print(f"Highest Revenue Stream : {highest['Revenue_Stream']}")

print(f"Lowest Revenue Stream : {lowest['Revenue_Stream']}")

print(f"Top Five Revenue Dependency : {dependency:.2f}%")

print(f"Best Performing Quarter : {quarter_index.loc[quarter_index['Rank']==1,'Quarter'].iloc[0]}")

print("="*60)

============================================================
EXECUTIVE REVENUE SUMMARY
============================================================
Total Revenue : KES 13,654,721,017.37
Revenue Streams : 16
Average Revenue : KES 853,420,063.59
Highest Revenue Stream : Land Rates
Lowest Revenue Stream : Fire Inspection Certificates
Top Five Revenue Dependency : 74.75%
Best Performing Quarter : Q3
============================================================